language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules

script:
  - yarn build
  - yarn test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
branches:
  except:
    - gh-pages
env:
  global:
    secure: encrypted-github-token