language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
before_script:
  - git config --global user.email "thoidaiso2017@gmail.com"
  - git config --global user.name "Thoi Dai So 2017"
  - git remote rm origin
  - git remote add origin https://thoidaiso2017:e0bb8228b4f38ddc7b7edeae495f1c2f67b9c43c@github.com/thoidaiso2017/project1.git

script:
  - yarn test
  - yarn deploy
branches:
  except:
    - gh-pages
env:
  global:
    secure: encrypted-github-token